2018-03-21T13:28:57.734Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 2 UNKNOWN: chaincode error (status: 500, message: Error: Failed to add object with ID '1002' as the object already exists)
    at new createStatusError (/home/moksh/IssueSecureAadhaar/node_modules/fabric-client/node_modules/grpc/src/client.js:64:15)
    at /home/moksh/IssueSecureAadhaar/node_modules/fabric-client/node_modules/grpc/src/client.js:583:15 {}$
2018-03-21T13:28:57.737Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: chaincode error (status: 500, message: Error: Failed to add object with ID '1002' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: 2 UNKNOWN: chaincode error (status: 500, message: Error: Failed to add object with ID '1002' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/moksh/IssueSecureAadhaar/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
